### ISSUE TITLE
Modify mood indicator 

### ISSUE THREAD

**Issue by claussian** [claussian/cattellhack#3]
To change the mood indicator from Low-Normal-High to [-5, +5] range. Add the ODI talk as a link to the readme for an explanation.

Higher granularity of mood data may lead to deeper insights of mood patterns based on temporal variation. Initial strategy of Low-Normal-High was to eliminate potential noise, but a better strategy would be to collect the variation and categorize them appropriately if necessary.

**Comment by jacattell** [comment]
Done

**Comment by jacattell** [comment]
Manually changed existing entries in spreadsheets
